config/routes.rb
Rails.application.routes.draw do
  root 'paths#new'
  resources :paths, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/path.rb
class Path < ApplicationRecord
  include HTTParty
  validates_presence_of :start_address, :end_address, :departs_at, :visit_duration
  #validate :path_within_london
  before_save :geocode_start_address
  before_save :geocode_end_address

  def set_travel_time!
    # Uncomment the following to enable Sidekiq job
    # CityMapperJob.perform_later(id)
    #
    begin
      base_uri = 'https://developer.citymapper.com/api/1/traveltime/'
      startcoord = "startcoord=#{[start_lat, start_lon].join('%2C')}"
      endcoord = "endcoord=#{[end_lat, end_lon].join('%2C')}"
      key = "key=#{Rails.application.secrets['citymapper_key']}"
      time = "time=#{departs_at}"
      str = "#{base_uri}?#{startcoord}&#{endcoord}&time_type=arrival&#{key}&#{time}"
      response = JSON.parse(HTTParty.get(str).body)
      update(travel_time: response['travel_time_minutes'])
    rescue Net::OpenTimeout, Net::ReadTimeout
      # Do some fancy logging
      {}
    end
  end

  def get_nearby_points
    raise 'A test exception.'
    begin
      city = 'London'
      lat = end_lat
      lng = end_lon
      rentify_api_call = "https://api.rentify.com/v2/properties.json?search%5Barea%5D=#{city}&search%5Blat%5D=#{lat}&search%5Blng%5D=#{lng}&search%5Bpage%5D=1&search%5Ball%5D=true"
    
      JSON.parse(HTTParty.get(rentify_api_call).body)
    rescue Exception => e
      puts e.message
    end
  end

  def geocode_start_address
    coordinates = Geocoder.coordinates start_address
    self.start_lat = coordinates[0]
    self.start_lon = coordinates[1]
  end

  def geocode_end_address
    coordinates = Geocoder.coordinates end_address
    self.end_lat = coordinates[0]
    self.end_lon = coordinates[1]
  end

  # TODO
  # Limit to London addresses
  # def path_within_london
  #   distance = 20
  #   center_point = [51.568449, -0.071068]
  #   box = Geocoder::Calculations.bounding_box(center_point, distance)
  #   msg = "cannot be outside of London"
  #   if !end_address.within_bounding_box(box)
  #     errors.add(:end_address, msg)
  #   elsif !start_address.within_bounding_box(box)
  #     errors.add(:start_address, msg)
  #   end
  # end
end

app/models/route.rb
class Route < ApplicationRecord
  include HTTParty
  validates_presence_of :start_address, :end_address, :departs_at, :visit_duration
  #validate :route_within_london
  before_save :geocode_start_address
  before_save :geocode_end_address

  def set_travel_time!
    # Uncomment the following to enable Sidekiq job
    # CityMapperJob.perform_later(id)
    #
    begin
      base_uri = 'https://developer.citymapper.com/api/1/traveltime/'
      startcoord = "startcoord=#{[start_lat, start_lon].join('%2C')}"
      endcoord = "endcoord=#{[end_lat, end_lon].join('%2C')}"
      key = "key=#{Rails.application.secrets['citymapper_key']}"
      time = "time=#{departs_at}"
      str = "#{base_uri}?#{startcoord}&#{endcoord}&time_type=arrival&#{key}&#{time}"
      response = JSON.parse(HTTParty.get(str).body)
      update(travel_time: response['travel_time_minutes'])
    rescue Net::OpenTimeout, Net::ReadTimeout
      # Do some fancy logging
      {}
    end
  end

  def geocode_start_address
    coordinates = Geocoder.coordinates start_address
    self.start_lat = coordinates[0]
    self.start_lon = coordinates[1]
  end

  def geocode_end_address
    coordinates = Geocoder.coordinates end_address
    self.end_lat = coordinates[0]
    self.end_lon = coordinates[1]
  end

  # TODO
  # Limit to London addresses
  # def route_within_london
  #   distance = 20
  #   center_point = [51.568449, -0.071068]
  #   box = Geocoder::Calculations.bounding_box(center_point, distance)
  #   msg = "cannot be outside of London"
  #   if !end_address.within_bounding_box(box)
  #     errors.add(:end_address, msg)
  #   elsif !start_address.within_bounding_box(box)
  #     errors.add(:start_address, msg)
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :set_path, only: [:show]
  
  def index
    @paths = Path.all
  end
  
  def new
    @path = Path.new
  end

  def create
    @path = Path.new path_params

    if @path.save
      @path.set_travel_time!
      redirect_to path_path(@path), notice: 'Path was successfully retrieved!'
    else
      render :new
    end
  end

  def show
    @nearby_points = @path.get_nearby_points
  end

  private
  def path_params
    params.require(:path).permit(
      :start_address,
      :end_address,
      :departs_at,
      :visit_duration)
  end

  def set_path
    @path = Path.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paths_helper.rb
module PathsHelper
  def expected_arrival_time(path)
    path.travel_time.minutes.from_now.strftime("%H:%M %P")
  end

  def start_address_value
    Path.count > 0 ? Path.last.end_address : '6-8 Long Lane, London EC1A 9HF'
  end

  def full_itinerary
    if @paths.present?
      content_tag :ul do
        time = @paths.first.departs_at.to_time
        expected = time + @paths.first.travel_time.minutes
        
        @paths.each_with_index do |path, i|
          if i > 0
            concat content_tag(:li, "Wait #{path.visit_duration} minutes...")
            time = expected + path.visit_duration.minutes
            expected = time + path.travel_time.minutes
          end
          
          concat content_tag(:li, "Depart from #{path.start_address} at #{time.strftime("%H:%M %P")} and arrive at #{path.end_address} by #{expected.strftime("%H:%M %P")} (travel time is #{path.travel_time} mins)")
        end
      end.html_safe
    else
      content_tag :ul do
        concat content_tag(:li, "No paths currently present.")
      end.html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="ui menu">
      <%= link_to "TravelTime App", root_path, class: 'header item' %>
      <%= link_to 'All paths', paths_path, class: 'item' %>
      <%= link_to 'New path', new_path_path, class: 'item' %>
    </div>
    <div class="ui container">
      <%= semantic_flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/paths/_form.html.erb
<% if @path.errors.any? %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      Bzzz....Brrr....There was a problem when submitting the form!  <%= pluralize(@path.errors.count, "error") %> prohibited this path from being saved:
    </div>
    <ul class="list">
    <% @path.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @path, html: {class: 'ui form'} do |f| %>
  <div class="two fields">
    <div class="field">
      <%= f.label :start_address %>
      <%= f.text_field :start_address, value: start_address_value %>
    </div>

    <div class="field">
      <%= f.label :end_address %>
      <%= f.text_field :end_address %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :departs_at %>
    <%= f.text_field :departs_at, value: Time.zone.now.iso8601 %>
  </div>

  <div class="field">
    <%= f.label :visit_duration %>
    <%= f.select(:visit_duration, options_for_select([
      ['15 mins', 15],
      ['30 mins', 30],
      ['45 mins', 45],
      ['60 mins', 60]], selected: 30)) %>
  </div>

  <div class="ui divider"></div>
  <%= f.submit 'Calculate!', class: 'ui button' %>
<% end %>

app/views/paths/index.html.erb
<h2 class="ui header">
  <i class="map icon"></i>
  <div class="content">
    All paths
    <div class="sub header">
       If you are going to travel to all paths, this is your expected itinerary:
    </div>
  </div>
</h2>

<%= full_itinerary %>

app/views/paths/new.html.erb
<h2>New travel path</h2>

<%= render 'form' %>

app/views/paths/show.html.erb
<h1>Showing path info</h1>
<%= "Path from <strong>#{@path.start_address}</strong> to <strong>#{@path.end_address}</strong>.".html_safe %>
<br>

<h2 class="ui header">
  <i class="car icon"></i>
  <div class="content">
    Travel time
    <div class="sub header">
      Journey travel time: <%= @path.travel_time %> minutes.
      If you leave now, your expected arrival time is <%= expected_arrival_time(@path) %>.
    </div>
  </div>
</h2>

<p>Nearby points:</p>

<% @nearby_points.with_indifferent_access[:properties].each do |property| %>
  <p>
    <%= property['uid'] %>
    <%= property['address'] %>
    <%= image_tag property['pic'] %>
  </p>
<% end %>

app/views/routes/_form.html.erb
<% if @route.errors.any? %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      Bzzz....Brrr....There was a problem when submitting the form!  <%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:
    </div>
    <ul class="list">
    <% @route.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @route, html: {class: 'ui form'} do |f| %>
  <div class="two fields">
    <div class="field">
      <%= f.label :start_address %>
      <%= f.text_field :start_address, value: start_address_value %>
    </div>

    <div class="field">
      <%= f.label :end_address %>
      <%= f.text_field :end_address %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :departs_at %>
    <%= f.text_field :departs_at, value: Time.zone.now.iso8601 %>
  </div>

  <div class="field">
    <%= f.label :visit_duration %>
    <%= f.select(:visit_duration, options_for_select([
      ['15 mins', 15],
      ['30 mins', 30],
      ['45 mins', 45],
      ['60 mins', 60]], selected: 30)) %>
  </div>

  <div class="ui divider"></div>
  <%= f.submit 'Calculate!', class: 'ui button' %>
<% end %>

app/views/routes/index.html.erb
<h2 class="ui header">
  <i class="map icon"></i>
  <div class="content">
    All routes
    <div class="sub header">
       If you are going to travel to all routes, this is your expected itinerary:
    </div>
  </div>
</h2>

<%= full_itinerary %>